package com.kaungyeehein.ktb.api.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class KtbKotobaJpCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public KtbKotobaJpCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ktb_jp_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ktb_jp_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ktb_jp_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ktb_jp_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ktb_jp_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ktb_jp_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ktb_jp_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ktb_jp_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ktb_jp_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ktb_jp_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ktb_jp_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ktb_jp_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKanaIsNull() {
            addCriterion("ktb_jp_kana is null");
            return (Criteria) this;
        }

        public Criteria andKanaIsNotNull() {
            addCriterion("ktb_jp_kana is not null");
            return (Criteria) this;
        }

        public Criteria andKanaEqualTo(String value) {
            addCriterion("ktb_jp_kana =", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaNotEqualTo(String value) {
            addCriterion("ktb_jp_kana <>", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaGreaterThan(String value) {
            addCriterion("ktb_jp_kana >", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaGreaterThanOrEqualTo(String value) {
            addCriterion("ktb_jp_kana >=", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaLessThan(String value) {
            addCriterion("ktb_jp_kana <", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaLessThanOrEqualTo(String value) {
            addCriterion("ktb_jp_kana <=", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaLike(String value) {
            addCriterion("ktb_jp_kana like", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaNotLike(String value) {
            addCriterion("ktb_jp_kana not like", value, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaIn(List<String> values) {
            addCriterion("ktb_jp_kana in", values, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaNotIn(List<String> values) {
            addCriterion("ktb_jp_kana not in", values, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaBetween(String value1, String value2) {
            addCriterion("ktb_jp_kana between", value1, value2, "kana");
            return (Criteria) this;
        }

        public Criteria andKanaNotBetween(String value1, String value2) {
            addCriterion("ktb_jp_kana not between", value1, value2, "kana");
            return (Criteria) this;
        }

        public Criteria andRomajiIsNull() {
            addCriterion("ktb_jp_romaji is null");
            return (Criteria) this;
        }

        public Criteria andRomajiIsNotNull() {
            addCriterion("ktb_jp_romaji is not null");
            return (Criteria) this;
        }

        public Criteria andRomajiEqualTo(String value) {
            addCriterion("ktb_jp_romaji =", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiNotEqualTo(String value) {
            addCriterion("ktb_jp_romaji <>", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiGreaterThan(String value) {
            addCriterion("ktb_jp_romaji >", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiGreaterThanOrEqualTo(String value) {
            addCriterion("ktb_jp_romaji >=", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiLessThan(String value) {
            addCriterion("ktb_jp_romaji <", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiLessThanOrEqualTo(String value) {
            addCriterion("ktb_jp_romaji <=", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiLike(String value) {
            addCriterion("ktb_jp_romaji like", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiNotLike(String value) {
            addCriterion("ktb_jp_romaji not like", value, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiIn(List<String> values) {
            addCriterion("ktb_jp_romaji in", values, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiNotIn(List<String> values) {
            addCriterion("ktb_jp_romaji not in", values, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiBetween(String value1, String value2) {
            addCriterion("ktb_jp_romaji between", value1, value2, "romaji");
            return (Criteria) this;
        }

        public Criteria andRomajiNotBetween(String value1, String value2) {
            addCriterion("ktb_jp_romaji not between", value1, value2, "romaji");
            return (Criteria) this;
        }

        public Criteria andKanjiIsNull() {
            addCriterion("ktb_jp_kanji is null");
            return (Criteria) this;
        }

        public Criteria andKanjiIsNotNull() {
            addCriterion("ktb_jp_kanji is not null");
            return (Criteria) this;
        }

        public Criteria andKanjiEqualTo(String value) {
            addCriterion("ktb_jp_kanji =", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiNotEqualTo(String value) {
            addCriterion("ktb_jp_kanji <>", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiGreaterThan(String value) {
            addCriterion("ktb_jp_kanji >", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiGreaterThanOrEqualTo(String value) {
            addCriterion("ktb_jp_kanji >=", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiLessThan(String value) {
            addCriterion("ktb_jp_kanji <", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiLessThanOrEqualTo(String value) {
            addCriterion("ktb_jp_kanji <=", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiLike(String value) {
            addCriterion("ktb_jp_kanji like", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiNotLike(String value) {
            addCriterion("ktb_jp_kanji not like", value, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiIn(List<String> values) {
            addCriterion("ktb_jp_kanji in", values, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiNotIn(List<String> values) {
            addCriterion("ktb_jp_kanji not in", values, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiBetween(String value1, String value2) {
            addCriterion("ktb_jp_kanji between", value1, value2, "kanji");
            return (Criteria) this;
        }

        public Criteria andKanjiNotBetween(String value1, String value2) {
            addCriterion("ktb_jp_kanji not between", value1, value2, "kanji");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("ktb_jp_level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("ktb_jp_level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(String value) {
            addCriterion("ktb_jp_level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(String value) {
            addCriterion("ktb_jp_level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(String value) {
            addCriterion("ktb_jp_level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(String value) {
            addCriterion("ktb_jp_level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(String value) {
            addCriterion("ktb_jp_level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(String value) {
            addCriterion("ktb_jp_level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLike(String value) {
            addCriterion("ktb_jp_level like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotLike(String value) {
            addCriterion("ktb_jp_level not like", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<String> values) {
            addCriterion("ktb_jp_level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<String> values) {
            addCriterion("ktb_jp_level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(String value1, String value2) {
            addCriterion("ktb_jp_level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(String value1, String value2) {
            addCriterion("ktb_jp_level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andChapterIsNull() {
            addCriterion("ktb_jp_chapter is null");
            return (Criteria) this;
        }

        public Criteria andChapterIsNotNull() {
            addCriterion("ktb_jp_chapter is not null");
            return (Criteria) this;
        }

        public Criteria andChapterEqualTo(Byte value) {
            addCriterion("ktb_jp_chapter =", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterNotEqualTo(Byte value) {
            addCriterion("ktb_jp_chapter <>", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterGreaterThan(Byte value) {
            addCriterion("ktb_jp_chapter >", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterGreaterThanOrEqualTo(Byte value) {
            addCriterion("ktb_jp_chapter >=", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterLessThan(Byte value) {
            addCriterion("ktb_jp_chapter <", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterLessThanOrEqualTo(Byte value) {
            addCriterion("ktb_jp_chapter <=", value, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterIn(List<Byte> values) {
            addCriterion("ktb_jp_chapter in", values, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterNotIn(List<Byte> values) {
            addCriterion("ktb_jp_chapter not in", values, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterBetween(Byte value1, Byte value2) {
            addCriterion("ktb_jp_chapter between", value1, value2, "chapter");
            return (Criteria) this;
        }

        public Criteria andChapterNotBetween(Byte value1, Byte value2) {
            addCriterion("ktb_jp_chapter not between", value1, value2, "chapter");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("ktb_jp_type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("ktb_jp_type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("ktb_jp_type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("ktb_jp_type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("ktb_jp_type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ktb_jp_type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("ktb_jp_type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("ktb_jp_type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("ktb_jp_type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("ktb_jp_type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("ktb_jp_type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("ktb_jp_type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("ktb_jp_type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("ktb_jp_type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSampleIsNull() {
            addCriterion("ktb_jp_sample is null");
            return (Criteria) this;
        }

        public Criteria andSampleIsNotNull() {
            addCriterion("ktb_jp_sample is not null");
            return (Criteria) this;
        }

        public Criteria andSampleEqualTo(String value) {
            addCriterion("ktb_jp_sample =", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleNotEqualTo(String value) {
            addCriterion("ktb_jp_sample <>", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleGreaterThan(String value) {
            addCriterion("ktb_jp_sample >", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleGreaterThanOrEqualTo(String value) {
            addCriterion("ktb_jp_sample >=", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleLessThan(String value) {
            addCriterion("ktb_jp_sample <", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleLessThanOrEqualTo(String value) {
            addCriterion("ktb_jp_sample <=", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleLike(String value) {
            addCriterion("ktb_jp_sample like", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleNotLike(String value) {
            addCriterion("ktb_jp_sample not like", value, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleIn(List<String> values) {
            addCriterion("ktb_jp_sample in", values, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleNotIn(List<String> values) {
            addCriterion("ktb_jp_sample not in", values, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleBetween(String value1, String value2) {
            addCriterion("ktb_jp_sample between", value1, value2, "sample");
            return (Criteria) this;
        }

        public Criteria andSampleNotBetween(String value1, String value2) {
            addCriterion("ktb_jp_sample not between", value1, value2, "sample");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("ktb_jp_create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("ktb_jp_create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("ktb_jp_create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("ktb_jp_create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("ktb_jp_create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ktb_jp_create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("ktb_jp_create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("ktb_jp_create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("ktb_jp_create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("ktb_jp_create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("ktb_jp_create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("ktb_jp_create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("ktb_jp_update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("ktb_jp_update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("ktb_jp_update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("ktb_jp_update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("ktb_jp_update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ktb_jp_update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("ktb_jp_update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("ktb_jp_update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("ktb_jp_update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("ktb_jp_update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("ktb_jp_update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("ktb_jp_update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("ktb_jp_delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("ktb_jp_delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("ktb_jp_delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("ktb_jp_delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("ktb_jp_delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ktb_jp_delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("ktb_jp_delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("ktb_jp_delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("ktb_jp_delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("ktb_jp_delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("ktb_jp_delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ktb_jp_delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andKanaLikeInsensitive(String value) {
            addCriterion("upper(ktb_jp_kana) like", value.toUpperCase(), "kana");
            return (Criteria) this;
        }

        public Criteria andRomajiLikeInsensitive(String value) {
            addCriterion("upper(ktb_jp_romaji) like", value.toUpperCase(), "romaji");
            return (Criteria) this;
        }

        public Criteria andKanjiLikeInsensitive(String value) {
            addCriterion("upper(ktb_jp_kanji) like", value.toUpperCase(), "kanji");
            return (Criteria) this;
        }

        public Criteria andLevelLikeInsensitive(String value) {
            addCriterion("upper(ktb_jp_level) like", value.toUpperCase(), "level");
            return (Criteria) this;
        }

        public Criteria andTypeLikeInsensitive(String value) {
            addCriterion("upper(ktb_jp_type) like", value.toUpperCase(), "type");
            return (Criteria) this;
        }

        public Criteria andSampleLikeInsensitive(String value) {
            addCriterion("upper(ktb_jp_sample) like", value.toUpperCase(), "sample");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ktb_kotoba_jp
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}