package com.kaungyeehein.ktb.api.mapper;

import com.kaungyeehein.ktb.api.domain.KtbKotobaEn;
import com.kaungyeehein.ktb.api.domain.KtbKotobaEnCriteria;
import com.kaungyeehein.ktb.api.domain.KtbKotobaEnKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KtbKotobaEnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    long countByExample(KtbKotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int deleteByExample(KtbKotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(KtbKotobaEnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int insert(KtbKotobaEn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int insertSelective(KtbKotobaEn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    List<KtbKotobaEn> selectByExampleWithRowbounds(KtbKotobaEnCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    List<KtbKotobaEn> selectByExample(KtbKotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    KtbKotobaEn selectByPrimaryKey(KtbKotobaEnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KtbKotobaEn record, @Param("example") KtbKotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KtbKotobaEn record, @Param("example") KtbKotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KtbKotobaEn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_en
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KtbKotobaEn record);
}