package com.kaungyeehein.ktb.api.mapper;

import com.kaungyeehein.ktb.api.domain.KtbKotobaMm;
import com.kaungyeehein.ktb.api.domain.KtbKotobaMmCriteria;
import com.kaungyeehein.ktb.api.domain.KtbKotobaMmKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KtbKotobaMmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    long countByExample(KtbKotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int deleteByExample(KtbKotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(KtbKotobaMmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int insert(KtbKotobaMm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int insertSelective(KtbKotobaMm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    List<KtbKotobaMm> selectByExampleWithRowbounds(KtbKotobaMmCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    List<KtbKotobaMm> selectByExample(KtbKotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    KtbKotobaMm selectByPrimaryKey(KtbKotobaMmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KtbKotobaMm record, @Param("example") KtbKotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KtbKotobaMm record, @Param("example") KtbKotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KtbKotobaMm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ktb_kotoba_mm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KtbKotobaMm record);
}