package com.kaungyeehein.kotoba.api.mapper.kotoba;

import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaMm;
import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaMmCriteria;
import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaMmKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KotobaMmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    long countByExample(KotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int deleteByExample(KotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(KotobaMmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int insert(KotobaMm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int insertSelective(KotobaMm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    List<KotobaMm> selectByExampleWithRowbounds(KotobaMmCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    List<KotobaMm> selectByExample(KotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    KotobaMm selectByPrimaryKey(KotobaMmKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KotobaMm record, @Param("example") KotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KotobaMm record, @Param("example") KotobaMmCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KotobaMm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_mm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KotobaMm record);
}