package com.kaungyeehein.kotoba.api.mapper.kotoba;

import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaEn;
import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaEnCriteria;
import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaEnKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KotobaEnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    long countByExample(KotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int deleteByExample(KotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(KotobaEnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int insert(KotobaEn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int insertSelective(KotobaEn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    List<KotobaEn> selectByExampleWithRowbounds(KotobaEnCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    List<KotobaEn> selectByExample(KotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    KotobaEn selectByPrimaryKey(KotobaEnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KotobaEn record, @Param("example") KotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KotobaEn record, @Param("example") KotobaEnCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KotobaEn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KotobaEn record);
}