package com.kaungyeehein.kotoba.api.mapper.kotoba;

import com.kaungyeehein.kotoba.api.domain.kotoba.Kotoba;
import com.kaungyeehein.kotoba.api.domain.kotoba.KotobaCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KotobaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    long countByExample(KotobaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int deleteByExample(KotobaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int insert(Kotoba record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int insertSelective(Kotoba record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    List<Kotoba> selectByExampleWithRowbounds(KotobaCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    List<Kotoba> selectByExample(KotobaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    Kotoba selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Kotoba record, @Param("example") KotobaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Kotoba record, @Param("example") KotobaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Kotoba record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Kotoba record);
}