package com.kaungyeehein.kotoba.api.domain.kotoba;

import java.io.Serializable;
import java.util.Date;

public class Kotoba implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_kana
     *
     * @mbg.generated
     */
    private String kana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_romaji
     *
     * @mbg.generated
     */
    private String romaji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_kanji
     *
     * @mbg.generated
     */
    private String kanji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_chapter
     *
     * @mbg.generated
     */
    private Byte chapter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_sample
     *
     * @mbg.generated
     */
    private String sample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba.kotoba_delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_id
     *
     * @return the value of kotoba.kotoba_id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_id
     *
     * @param id the value for kotoba.kotoba_id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_kana
     *
     * @return the value of kotoba.kotoba_kana
     *
     * @mbg.generated
     */
    public String getKana() {
        return kana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_kana
     *
     * @param kana the value for kotoba.kotoba_kana
     *
     * @mbg.generated
     */
    public void setKana(String kana) {
        this.kana = kana == null ? null : kana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_romaji
     *
     * @return the value of kotoba.kotoba_romaji
     *
     * @mbg.generated
     */
    public String getRomaji() {
        return romaji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_romaji
     *
     * @param romaji the value for kotoba.kotoba_romaji
     *
     * @mbg.generated
     */
    public void setRomaji(String romaji) {
        this.romaji = romaji == null ? null : romaji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_kanji
     *
     * @return the value of kotoba.kotoba_kanji
     *
     * @mbg.generated
     */
    public String getKanji() {
        return kanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_kanji
     *
     * @param kanji the value for kotoba.kotoba_kanji
     *
     * @mbg.generated
     */
    public void setKanji(String kanji) {
        this.kanji = kanji == null ? null : kanji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_level
     *
     * @return the value of kotoba.kotoba_level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_level
     *
     * @param level the value for kotoba.kotoba_level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_chapter
     *
     * @return the value of kotoba.kotoba_chapter
     *
     * @mbg.generated
     */
    public Byte getChapter() {
        return chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_chapter
     *
     * @param chapter the value for kotoba.kotoba_chapter
     *
     * @mbg.generated
     */
    public void setChapter(Byte chapter) {
        this.chapter = chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_type
     *
     * @return the value of kotoba.kotoba_type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_type
     *
     * @param type the value for kotoba.kotoba_type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_sample
     *
     * @return the value of kotoba.kotoba_sample
     *
     * @mbg.generated
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_sample
     *
     * @param sample the value for kotoba.kotoba_sample
     *
     * @mbg.generated
     */
    public void setSample(String sample) {
        this.sample = sample == null ? null : sample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_create_date
     *
     * @return the value of kotoba.kotoba_create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_create_date
     *
     * @param createDate the value for kotoba.kotoba_create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_update_date
     *
     * @return the value of kotoba.kotoba_update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_update_date
     *
     * @param updateDate the value for kotoba.kotoba_update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba.kotoba_delete_flag
     *
     * @return the value of kotoba.kotoba_delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba.kotoba_delete_flag
     *
     * @param deleteFlag the value for kotoba.kotoba_delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Kotoba other = (Kotoba) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getKana() == null ? other.getKana() == null : this.getKana().equals(other.getKana()))
            && (this.getRomaji() == null ? other.getRomaji() == null : this.getRomaji().equals(other.getRomaji()))
            && (this.getKanji() == null ? other.getKanji() == null : this.getKanji().equals(other.getKanji()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getChapter() == null ? other.getChapter() == null : this.getChapter().equals(other.getChapter()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getSample() == null ? other.getSample() == null : this.getSample().equals(other.getSample()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getKana() == null) ? 0 : getKana().hashCode());
        result = prime * result + ((getRomaji() == null) ? 0 : getRomaji().hashCode());
        result = prime * result + ((getKanji() == null) ? 0 : getKanji().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getChapter() == null) ? 0 : getChapter().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getSample() == null) ? 0 : getSample().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", kana=").append(kana);
        sb.append(", romaji=").append(romaji);
        sb.append(", kanji=").append(kanji);
        sb.append(", level=").append(level);
        sb.append(", chapter=").append(chapter);
        sb.append(", type=").append(type);
        sb.append(", sample=").append(sample);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}