package com.kaungyeehein.kotoba.api.domain.kotoba;

import java.io.Serializable;

public class KotobaEn extends KotobaEnKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba_en.kotoba_sample
     *
     * @mbg.generated
     */
    private String sample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kotoba_en.kotoba_delete_flag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba_en.kotoba_sample
     *
     * @return the value of kotoba_en.kotoba_sample
     *
     * @mbg.generated
     */
    public String getSample() {
        return sample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba_en.kotoba_sample
     *
     * @param sample the value for kotoba_en.kotoba_sample
     *
     * @mbg.generated
     */
    public void setSample(String sample) {
        this.sample = sample == null ? null : sample.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kotoba_en.kotoba_delete_flag
     *
     * @return the value of kotoba_en.kotoba_delete_flag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kotoba_en.kotoba_delete_flag
     *
     * @param deleteFlag the value for kotoba_en.kotoba_delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        KotobaEn other = (KotobaEn) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSample() == null ? other.getSample() == null : this.getSample().equals(other.getSample()))
            && (this.getDeleteFlag() == null ? other.getDeleteFlag() == null : this.getDeleteFlag().equals(other.getDeleteFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSample() == null) ? 0 : getSample().hashCode());
        result = prime * result + ((getDeleteFlag() == null) ? 0 : getDeleteFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kotoba_en
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sample=").append(sample);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}